runtime: go
api_version: go1
application: githubcompare-backend
version: v1

handlers:
- url: /api/admin/.*
  script: _go_app
  login: admin
- url: /api/.*
  script: _go_app
- url: /lib
  static_dir: web/lib
- url: /
  static_files: web/index.html
  upload: web/index.html
- url: .*
  static_dir: web

inbound_services:
- warmup